name: Deploy static site to Azure Web App - peiwast-test-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: app/

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: static-site

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B2129CAF87D54A418462763866AE6BBB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0CABA4BCD7D04C8A92534DE85C1A177F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_10DCF0289BEB457D90E502C6CCFD69C5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'peiwast-test-app'
          slot-name: 'Production'
          package: app/